const PUBLIC_SUPABASE_URL =
	import.meta.env.VITE_PUBLIC_SUPABASE_URL ?? import.meta.env.PUBLIC_SUPABASE_URL ?? '';
const PUBLIC_SUPABASE_ANON_KEY =
	import.meta.env.VITE_PUBLIC_SUPABASE_ANON_KEY ?? import.meta.env.PUBLIC_SUPABASE_ANON_KEY ?? '';

export { PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY };
